services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php84
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_net
    dns:
      8.8.8.8

  mariadb:
    container_name: ${DB_HOST}
    image: mariadb:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./src/Database:/docker-entrypoint-initdb.d  # << Add this line
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_MYSQL}
      MARIADB_DATABASE: ${DB_DATABASE_MYSQL}
    networks:
      - app_net

networks:
  app_net:

